### ISSUE TITLE
Add factorial 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ExtremeDude2/cmd-calculator#1]
```
No srly do it, this is mostly just a reminder
```

Original issue reported on code.google.com by `ExtremeD...@gmail.com` on 5 Feb 2014 at 9:58

**Comment by ExtremeDude2** [comment]
onice! i forgot

**Comment by cxd4** [comment]
wow such code
much object
very stack
professor Stoustrupe will cry

**Comment by ExtremeDude2** [comment]
Fixed in df1b018dcef410aef0b7b7211c22a108273af4b6
